%YAML:1.0

#common parameters
savePath: "/home/yanhao/LaserCameraCal_ws/data/"
bag_path: "/home/yanhao/LaserCameraCal_ws/data/2019-10-15-20-12-05.bag"

scan_topic_name: "/scan"
img_topic_name: "/camera/image_raw"

# tag info
tag_type: 1 # 1: kalibr_tag, 2: apriltag
tag_size: 0.0451 # tag size, unit meter
tag_spacing: 0.3 # tag spacing, only used in kalibr_tag. For details, please see kalibr tag description.
black_border: 2 # if you use kalibr_tag black_boarder = 2; if you use apriltag black_boarder = 1
 
#camera calibration 
model_type: KANNALA_BRANDT
camera_name: cam0
image_width: 2048
image_height: 1536

projection_parameters:
   mu: 1115.3458479831127
   mv: 1115.5680569978117
   u0: 1047.8994454164401
   v0: 775.5928959466218
   k2: -0.39561955371546687
   k3: 0.14301415731672948
   k4: -0.00091786036772837
   k5: -0.0011805174547034807

